### ISSUE TITLE
Missing ;

### ISSUE THREAD

**Issue by Kalail** [ThatRozebudDude/FPS-Plus-Public#80]
![изображение_2024-07-19_002345664](https://github.com/user-attachments/assets/4912e5dd-b96d-4f85-bed4-babefce6cb79)
![изображение_2024-07-19_002357490](https://github.com/user-attachments/assets/88868553-b131-4102-85be-1507059a5481)
what

**Comment by ThatRozebudDude** [comment]
The error appears to be in a different file with a lowercase "m" instead of a capital "M".

**Comment by biomseed** [comment]
This isn't a problem with the engine because Miku.hx doesn't exist. If you coded this, know that this section is not for programming help. The better place to find that is the discussion tab of the base Funkin' repo, which is meant for that kind of stuff. Anyway, I don't think this error is real (I don't believe you faked it either way, I'm just saying the compiler could somehow be confused) because "Miku.hx" isn't capitalized in the error. Try to clean with lime or something and then try again. If all else fails, look for the equivalent of a try statement (or whatever bypasses errors) in haxe and use that.

**Comment by Kalail** [comment]
t h a n k s

**Comment by biomseed** [comment]
Make sure to close the issue since this place isn't meant for programming help, it just causes clutter to leave it open
