### ISSUE TITLE
Parents, BF & GF slightly filtered in the `MallErect` stage

### ISSUE THREAD

**Issue by doggogit** [ThatRozebudDude/FPS-Plus-Public#99]
# Steps to reproduce:
- Go to the `Erect` category
- Pick either Cocoa or Eggnog
----
![image](https://github.com/user-attachments/assets/db21f7af-e9f6-4320-845c-8784d09b4a83)

**Comment by doggogit** [comment]
After further investigation, it seems that this filter/saturation is present in base game, but not as INTENSE as in FPS+
(best example I can give is the whiter part of BF's mic hand, as shown in the image below)
((this is a nitpick but my eyes don't like it 😭)

----
![image](https://github.com/user-attachments/assets/d7e32bdd-a51f-4b16-a2d0-8ec838b4a737)

**Comment by ThatRozebudDude** [comment]
This is actually a problem with base game, if you look in the FLA for the erect stage it looks like how it does in FPS Plus. The AdjustColor shader used in the current release of base game isn't 100% accurate to how Flash works, specifically contrast and saturation are scaled up when using positive values for them along with a few other strange behaviors.

Personally, I'm not exactly the biggest fan of how it looks either, so if they wanna tone it down a bit in base game with the updated shader I'll update this too, but I'm leaving it for now since this is technically more accurate to the intended look of the game.

![Screenshot from Adobe Animate](https://github.com/user-attachments/assets/72fe3096-3b17-49dd-a350-8a6ed411cb55)

**Comment by doggogit** [comment]
> This is actually a problem with base game, if you look in the FLA for the erect stage it looks like how it does in FPS Plus. The AdjustColor shader used in the current release of base game isn't 100% accurate to how Flash works, specifically contrast and saturation are scaled up when using positive values for them along with a few other strange behaviors.
> 
> Personally, I'm not exactly the biggest fan of how it looks either, so if they wanna tone it down a bit in base game with the updated shader I'll update this too, but I'm leaving it for now since this is technically more accurate to the intended look of the game.
> 
> ![Screenshot from Adobe Animate](https://private-user-images.githubusercontent.com/35246975/375940283-72fe3096-3b17-49dd-a350-8a6ed411cb55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MzUyMjMsIm5iZiI6MTcyODczNDkyMywicGF0aCI6Ii8zNTI0Njk3NS8zNzU5NDAyODMtNzJmZTMwOTYtM2IxNy00OWRkLWEzNTAtOGE2ZWQ0MTFjYjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDEyMDg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ZWQ5OGYyMTM4MzU5MzA5NmExNjA1NmExYjdiZTNiNmIyZDZkYmQ0N2RhMzAwMjVkZjA3YmYzNTJhNzU1MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oceqW8BE1o2pm5kBIYXSDq0Xc46n0bDLmjZcGB9eI5w)

Ohh I see, okay.. Yeah, I'm not a fan of it either, LOL
